# Generated by Django 4.0.3 on 2022-03-26 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=255)),
                ('time_table', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('number_of_comments', models.PositiveIntegerField(blank=True, default=0)),
                ('sum_of_rate', models.PositiveIntegerField(blank=True, default=0)),
                ('rate', models.FloatField(blank=True, default=0)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.employerprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whats_app', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('courses_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('instagram', models.CharField(max_length=250)),
                ('video', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number_of_free_places', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_per_month', models.PositiveIntegerField()),
                ('time_table', models.CharField(max_length=255)),
                ('lesson_duration', models.CharField(max_length=255)),
                ('programm', models.TextField()),
                ('sale', models.CharField(blank=True, max_length=255, null=True)),
                ('formats', models.PositiveSmallIntegerField(choices=[(1, 'Онлайн'), (2, 'Оффлайн')])),
                ('courses_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_comments', models.PositiveIntegerField(blank=True, default=0)),
                ('sum_of_rate', models.PositiveIntegerField(blank=True, default=0)),
                ('rate', models.FloatField(blank=True, default=0)),
                ('category', models.ManyToManyField(to='categories.category')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.educationcentreprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
