from django.contrib import admin
from user_relation_choice.models import UserRelationChoiceCourses, UserRelationChoiceEducationCentreProfile, UserRelationChoiceInternShip, UserRelationChoiceTeacherProfile


admin.site.register(UserRelationChoiceTeacherProfile)
admin.site.register(UserRelationChoiceEducationCentreProfile)
admin.site.register(UserRelationChoiceCourses)
admin.site.register(UserRelationChoiceInternShip)