# Generated by Django 4.0.3 on 2022-03-13 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_alter_user_is_active_alter_user_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relation_choice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationChoiceTeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Плохо'), (2, 'Мне не очень понравилось'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отличная статья')])),
                ('comments', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.teacherprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
