# Generated by Django 4.0.3 on 2022-03-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0015_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NonProfitOrganizationProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.nonprofitorganizationprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationCentrePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.educationcentreprofile')),
            ],
        ),
    ]
